### ISSUE TITLE
Finnish invoice addon for v15 does not do anything?

### ISSUE THREAD

**Issue by ossimantylahti** [avoinsystems/avoinsystems-addons#22]
Installing the Finnish invoices extension for Odoo v15 does not seem to be doing anything. Sending and printing invoices just result to default Odoo PDF. Are there any specific steps that need to be taken to enable this?

(Odoo App store version 13 mentioned that ""Please note that using this template with email requires setting the invoice template to the email template manually."). What exactly is needed to enable this?

**Comment by aisopuro** [comment]
@ossimantylahti the module is marked `installable: False` in the manifest in v15 at time of writing: https://github.com/avoinsystems/avoinsystems-addons/blob/ca03143f91bafd27dc698356c5424151ea85dc94/l10n_fi_invoice/__manifest__.py#L23

It has not been migrated to version 15. If you have an entirely new Odoo at v15, it shouldn't have let you install the module at all. If you are migrating a previous Odoo version to 15, then the module may remain installed, even though it is marked as uninstallable in the new version. So it isn't expected to work in version 15. We also unfortunately don't have concrete plans at the moment to port it a new version as far as I'm aware. PRs are welcome.

Regarding the "using this template with email requires setting the invoice template to the email template manually" instruction, it basically means:
* Normally when you send an invoice via email, you are shown a preview where you can edit the body of the message, and it also shows the PDF it is about to send as an attachment
* This module does not automatically replace the PDF: rather you have to set it yourself. Either by replacing it per-message (useful if you only need it for some invoices) or by changing it on the template's settings (useful if you always want this PDF).

If you want to change the setting on the template, Odoo should allow you to open the template for editing when you are in the process of sending the invoice. If it doesn't, you can also go to Settings -> Technical [You need to be in developer mode for this] -> Email -> Templates. There you should be able to find the "Invoice: Send by email" template.

On the template settings, you can then set the desired report (PDF) to attach:

![image](https://user-images.githubusercontent.com/2587901/150295492-86d4b744-430b-43dc-82ca-e2e908a91ed0.png)

Choose "Finnish Invoice" instead of "Invoices" and that should make it so the finnish version is sent instead of the usual one. This at least in version 13: like I said, this hasn't been ported to 15.

I'll close this issue as I believe I've answered the questions raised.
